language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
addons:
  postgresql: "9.4"
services:
  - postgresql
env:
  - SECRET=testing PORT=8000 REGION=en ACCESS_TOKEN_EXPIRY=3600 DB_NAME=wishlist DB_USERNAME=wishlist DB_PASSWORD='' API_VERSION=1
before_script:
    - psql -c 'create user wishlist with SUPERUSER CREATEROLE CREATEDB REPLICATION PASSWORD "";' -U postgres
