language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
sudo: false
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
services:
  - postgresql
env:
  - CXX=g++-4.8
before_script:
    - echo $'SECRET=testing\nPORT=8000\nREGION=en\nACCESS_TOKEN_EXPIRY=3600\nAPI_VERSION=1\nPGDATABASE=wishlist\nPGUSER=wishlist\nPGPASSWORD=""' > .env
    - psql -c 'create user wishlist with SUPERUSER CREATEROLE CREATEDB REPLICATION;' -U postgres
